APT::FTPArchive::Release {
    Origin "Team ISET";
    Label "Team ISET Software Repository";
    Suite "stable";
    Codename "main";

    Version "1.0";

    Architectures "amd64";
    Components "main";

    Description "The Debian package repository that provided by Team ISET.";

    Acquire-By-Hash "yes";
}