Dir {
    ArchiveDir ".";
    CacheDir "cache";
};

Default {
    Packages::Compress ". gzip xz";
};

TreeDefault {
    Directory "pool";
};

Tree "dists/stable" {
    Sections "main";
    Architectures "amd64";
};
